//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyPaymentCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartyPaymentCollection()
        {
            this.PartySupplyItems = new HashSet<PartySupplyItem>();
        }
    
        public int PartyPaymentCollectionId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PartyId { get; set; }
        public string Particular { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMode { get; set; }
        public string Remarks { get; set; }
        public string TransactionNo { get; set; }
        public string ChequeNo { get; set; }
        public string DDNO { get; set; }
        public byte Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartySupplyItem> PartySupplyItems { get; set; }
    }
}
