//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartySupplyItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartySupplyItem()
        {
            this.PartyPaymentDetails = new HashSet<PartyPaymentDetail>();
        }
    
        public int PartySupplyItemId { get; set; }
        public System.DateTime SupplyDate { get; set; }
        public int PartyId { get; set; }
        public string InvoiceNo { get; set; }
        public string Particular { get; set; }
        public string Attachement { get; set; }
        public string FileFormat { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public byte Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> PartyPaymentCollectionId { get; set; }
    
        public virtual PartyPaymentCollection PartyPaymentCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyPaymentDetail> PartyPaymentDetails { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
        public virtual PartyDetail PartyDetail { get; set; }
    }
}
